language: python

postgresql:
  enabled: false

webapp:
  podAnnotations:
    qonto.co/monitoring.priority: P3
    qonto.co/monitoring.service: airbyte
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"

airbyte-bootloader:
  enabled: true
  podAnnotations:
    qonto.co/monitoring.priority: P3
    qonto.co/monitoring.service: airbyte
    "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
  resources:
    limits:
      memory: 200Mi
    requests:
      cpu: 0.6
      memory: 200Mi
